
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 09 12:46:26 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoCUP/ClaseLexica {
  /* terminals */
  public static final int MENOS = 9;
  public static final int OpLE = 5;
  public static final int CONCAT = 17;
  public static final int IDEN = 3;
  public static final int LMAP = 19;
  public static final int OpNEQ = 7;
  public static final int POR = 10;
  public static final int OpGE = 4;
  public static final int ASS = 15;
  public static final int LB = 12;
  public static final int OpEQ = 6;
  public static final int RB = 13;
  public static final int COMA = 14;
  public static final int LFILTER = 20;
  public static final int EOF = 0;
  public static final int LREDUCE = 18;
  public static final int DIV = 11;
  public static final int Num = 2;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int MAS = 8;
}

