
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 10 13:39:11 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int Lfilter = 20;
  public static final int Lreduce = 18;
  public static final int OpLE = 5;
  public static final int Mas = 8;
  public static final int Iden = 3;
  public static final int Lmap = 19;
  public static final int OpNEQ = 7;
  public static final int Print = 16;
  public static final int Coma = 14;
  public static final int OpGE = 4;
  public static final int OpEQ = 6;
  public static final int EOF = 0;
  public static final int Por = 10;
  public static final int Num = 2;
  public static final int Ass = 15;
  public static final int error = 1;
  public static final int Concat = 17;
  public static final int Menos = 9;
  public static final int Lb = 12;
  public static final int Rb = 13;
  public static final int Div = 11;
}

